# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import pyas2.as2utils
import pyas2.models


class Migration(migrations.Migration):

    dependencies = [
        ('pyas2', '0014_auto_20160420_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='https_ca_cert',
            field=pyas2.as2utils.EphemeralFileField(blank=True, help_text=b'File must exist on target system already.  Uploading only sets path/name, uploaded file content is discarded.', null=True, storage=pyas2.as2utils.EphemeralFileSystemStorage(), upload_to=pyas2.models.cert_path, verbose_name='HTTPS Local CA Store'),
        ),
        migrations.AlterField(
            model_name='privatecertificate',
            name='ca_cert',
            field=pyas2.as2utils.EphemeralFileField(blank=True, help_text=b'File must exist on target system already.  Uploading only sets path/name, uploaded file content is discarded.', null=True, storage=pyas2.as2utils.EphemeralFileSystemStorage(), upload_to=pyas2.models.cert_path, verbose_name='Local CA Store'),
        ),
        migrations.AlterField(
            model_name='privatecertificate',
            name='certificate',
            field=pyas2.as2utils.EphemeralFileField(help_text=b'File must exist on target system already.  Uploading only sets path/name, uploaded file content is discarded.', storage=pyas2.as2utils.EphemeralFileSystemStorage(), upload_to=pyas2.models.cert_path),
        ),
        migrations.AlterField(
            model_name='privatecertificate',
            name='certificate_passphrase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publiccertificate',
            name='ca_cert',
            field=pyas2.as2utils.EphemeralFileField(blank=True, help_text=b'File must exist on target system already.  Uploading only sets path/name, uploaded file content is discarded.', null=True, storage=pyas2.as2utils.EphemeralFileSystemStorage(), upload_to=pyas2.models.cert_path, verbose_name='Local CA Store'),
        ),
        migrations.AlterField(
            model_name='publiccertificate',
            name='certificate',
            field=pyas2.as2utils.EphemeralFileField(help_text=b'File must exist on target system already.  Uploading only sets path/name, uploaded file content is discarded.', storage=pyas2.as2utils.EphemeralFileSystemStorage(), upload_to=pyas2.models.cert_path),
        ),
    ]
